### ISSUE TITLE
Decrease wait time for commands

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-raspberry-pi-controller#50]
Hey @TimEvWw, Rick and I were messing with the latest bot and found that commands had a delay of about a minute. We looked into the controller source code and found this:

https://github.com/FarmBot/farmbot-raspberry-pi-controller/blob/bbc816cb80ad84150404a26872ff75660da93c42/lib/controller.rb#L128

Is there a reason the `+ 60` is there?

**Comment by TimEvWw** [comment]
The idea there is that the system waits for a refresh signal during one
minute (it's named 'refresh' because I use this method a lot to trigger
screen refreshes when new data arrives). If after one minute there is no
signal received, it will check the database to see if a command has been
received without setting the refresh flag. So that signal goes wrong. That
would explain it.

**Comment by RickCarlino** [comment]
Do you think there will be any repercussions for lowering the number lower, like to `1`?

**Comment by TimEvWw** [comment]
Higher system load mainly. SQLite was a bit sluggish for continuous polling
for my taste (hence the refresh system) but it works as a quick fix.

**Comment by roryaronson** [comment]
Ok, so menu.rb is scheduling a command, but not setting the refresh flag?

I removed the +60 altogether locally and watched the CPU go to 85% haha

**Comment by TimEvWw** [comment]
I think that the setting of the flag was done in the same routine as writing of the command but it was lost in refactoring. Will check.

Op 24-feb.-2015 om 22:35 heeft Rory Aronson <notifications@github.com> het volgende geschreven:

**Comment by TimEvWw** [comment]
Refresh is modified.
