### ISSUE TITLE
@dbaccess is nil in MessageHandler

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-raspberry-pi-controller#51]
Hey Tim,

any idea why @dbaccess is nil in `MessageHandler`?

```ruby
class MessageHandler
  def initialize
    # . . . 
    @dbaccess = $dbaccess
  end
end
```

**Comment by TimEvWw** [comment]
I used one shared db access stored in $dbaccess for all modules. This is normally instantiated in farmbot.rb 

Op 25-feb.-2015 om 05:33 heeft Rick Carlino <notifications@github.com> het volgende geschreven:

**Comment by TimEvWw** [comment]
It just takes the RPi a long time to start up db access (seconds while on a PC this is fractions of a second) so doing it once instead of multiple times (for each class separate db access) made the software start up a bit faster.

Op 25-feb.-2015 om 05:33 heeft Rick Carlino <notifications@github.com> het volgende geschreven:

**Comment by roryaronson** [comment]
Perhaps when we upgrade to Raspberry Pi 2's performance issues like that will be less of an issue ;)

@TimEvWw, hop onto g-chat if you can!

**Comment by TimEvWw** [comment]
Given that the RPi2 also runs on a SD card, and is only a few times faster, upgrading will help but won't be a cure all.

G-chat in an hour and half.

Op 25-feb.-2015 om 05:58 heeft Rory Aronson <notifications@github.com> het volgende geschreven:

**Comment by TimEvWw** [comment]
If you run it now with farmtalk.rb, dbaccess is set.
